services:
  - type: web
    name: logiscore-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres:[YOUR-SUPABASE-PASSWORD]@db.[YOUR-PROJECT-REF].supabase.co:5432/postgres
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        value: sk_test_your_stripe_key_here
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_your_stripe_key_here
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_your_webhook_secret_here
      - key: STRIPE_SHIPPER_MONTHLY_PRICE_ID
        value: price_your_shipper_monthly_price_id_here
      - key: STRIPE_SHIPPER_ANNUAL_PRICE_ID
        value: price_your_shipper_annual_price_id_here
      - key: STRIPE_FORWARDER_MONTHLY_PRICE_ID
        value: price_your_forwarder_monthly_price_id_here
      - key: STRIPE_FORWARDER_ANNUAL_PRICE_ID
        value: price_your_forwarder_annual_price_id_here
      - key: STRIPE_FORWARDER_ANNUAL_PLUS_PRICE_ID
        value: price_your_forwarder_annual_plus_price_id_here
      - key: CRON_SECRET_KEY
        generateValue: true

  - type: cron
    name: admin-daily-summary
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "0 22 * * *"
    command: python3 scripts/run_admin_daily_summary.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres:[YOUR-SUPABASE-PASSWORD]@db.[YOUR-PROJECT-REF].supabase.co:5432/postgres
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        value: sk_test_your_stripe_key_here
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_your_stripe_key_here
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_your_webhook_secret_here
      - key: STRIPE_SHIPPER_MONTHLY_PRICE_ID
        value: price_your_shipper_monthly_price_id_here
      - key: STRIPE_SHIPPER_ANNUAL_PRICE_ID
        value: price_your_shipper_annual_price_id_here
      - key: STRIPE_FORWARDER_MONTHLY_PRICE_ID
        value: price_your_forwarder_monthly_price_id_here
      - key: STRIPE_FORWARDER_ANNUAL_PRICE_ID
        value: price_your_forwarder_annual_price_id_here
      - key: STRIPE_FORWARDER_ANNUAL_PLUS_PRICE_ID
        value: price_your_forwarder_annual_plus_price_id_here
      - key: CRON_SECRET_KEY
        generateValue: true

 